#!/bin/sh
#                               -*- Mode: Sh -*- 
# dvt-cron --- 
# Author           : Manoj Srivastava ( srivasta@glaurung.green-gryphon.com ) 
# Created On       : Mon Oct 20 23:16:09 2003
# Created On Node  : glaurung.green-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Wed Oct 29 15:28:06 2003
# Last Machine Used: glaurung.green-gryphon.com
# Update Count     : 3
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# 
#  arch-tag: a2a18726-358e-46e5-bc85-bce4eff4e5a3
# 

# This script is a part of the Devotee package, and is 
# Copyright (c) 2002 Manoj Srivastava <srivasta@debian.org>
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


set -e

workdir=/org/vote.debian.org/
test -d $workdir || exit 1

date
cd $workdir

PATH=$workdir/bin:$PATH
export PATH

HTML_DIR=$HOME/public_html

vote="$1"
conffile=./data/$vote/devotee.conf

./bin/dvt-cp       -c $conffile
echo Copying Done

./bin/dvt-mime     -c $conffile
echo mime decoding done

./bin/dvt-gpg      -c $conffile
echo GPG checks done

./bin/dvt-ldap     -c $conffile
echo LDAP checks done

./bin/dvt-extract  -c $conffile
echo extracted message

./bin/dvt-parse    -c $conffile
echo Parsed ballot

./bin/dvt-gack     -c $conffile
echo generated ack

./bin/dvt-nack     -c $conffile
echo sent out error messages

./bin/dvt-ack     -c $conffile
echo sent out acks

./bin/dvt-voters    -c $conffile
echo generated list of voters

./bin/dvt-tally     -c $conffile 
echo did the dummy tally sheet

./bin/dvt-tally   --final_tally   -c $conffile 
echo tallying done

./bin/dvt-rslt -c $conffile 
echo Calculated results

if [ -d $HTML_DIR ]; then
   cp -f ./data/${vote}/voters.txt      $HTML_DIR/${vote}_voters.txt;
   cp -f ./data/${vote}/dummy_tally.txt $HTML_DIR/dummy_${vote}_tally.txt
fi

uids=$(cd $workdir/data/$vote/ldap/; egrep ^uid: $(cd ../tally; ls -1 *.raw) 2>/dev/null | sed -e 's/^.*uid://' | sort | uniq -c | wc -l);
tally=$(ls -1 $workdir/data/$vote/tally/*.raw 2>/dev/null | wc -l; )
outfile=./data/${vote}/timeline/results.$(date +%s).txt
echo "The total numbers of votes tallied = $uids" >> ./data/${vote}/results.txt
if [ -d ./data/${vote}/timeline ]; then
   cp -f ./data/${vote}/results.txt $outfile
fi

echo cleaning up
find ./data/${vote}/tmp/ -type f -exec rm {} \;

