#!/bin/sh
#                               -*- Mode: Sh -*- 
# dvt-cron --- 
# Author           : Manoj Srivastava ( srivasta@glaurung.green-gryphon.com ) 
# Created On       : Mon Oct 20 23:16:09 2003
# Created On Node  : glaurung.green-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Tue Apr  5 00:41:57 2005
# Last Machine Used: glaurung.internal.golden-gryphon.com
# Update Count     : 7
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# 
#  arch-tag: a2a18726-358e-46e5-bc85-bce4eff4e5a3
# 

# This script is a part of the Devotee package, and is 
# Copyright (c) 2002 Manoj Srivastava <srivasta@debian.org>
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


set -e

basedir=/org/vote.debian.org/
test -d $basedir || exit 1

BALLOTDIR=$basedir/ballots/

html_dir="$HOME/public_html"


ballots=$(find $BALLOTDIR -type f -name \*.blt);



date
cd $basedir

PATH=$basedir/bin:$PATH
export PATH

for ballot in $ballots; do
    vote=$(basename $ballot .blt; )
    conffile=$basedir/data/$vote/devotee.conf

    if [ -e "$conffile" ]; then
        $basedir/bin/dvt-cp       -c $conffile
        echo Copying Done for $vote

        $basedir/bin/dvt-mime     -c $conffile
        echo mime decoding done for $vote

        $basedir/bin/dvt-gpg      -c $conffile
        echo GPG checks done for $vote

        $basedir/bin/dvt-ldap     -c $conffile
        echo LDAP checks done for $vote

        $basedir/bin/dvt-extract  -c $conffile
        echo extracted message for $vote

        $basedir/bin/dvt-parse    -c $conffile
        echo Parsed ballot for $vote

        $basedir/bin/dvt-gack     -c $conffile
        echo generated ack for $vote

        $basedir/bin/dvt-nack     -c $conffile
        echo sent out error messages for $vote

        $basedir/bin/dvt-ack     -c $conffile
        echo sent out acks for $vote

        $basedir/bin/dvt-voters    -c $conffile
        echo generated list of voters for $vote

        $basedir/bin/dvt-tally     -c $conffile 
        echo did the dummy tally sheet for $vote

        $basedir/bin/dvt-tally   --final_tally   -c $conffile 
        echo tallying done for $vote

        $basedir/bin/dvt-rslt -c $conffile 
        echo Calculated results for $vote

        if [ -d $html_dir ]; then
            cp -f $basedir/data/${vote}/voters.txt      $html_dir/${vote}_voters.txt;
            cp -f $basedir/data/${vote}/dummy_tally.txt $html_dir/dummy_${vote}_tally.txt
        fi

        uids=$(cd $basedir/data/$vote/ldap/; egrep ^uid: $(cd .$basedir/tally; ls -1 *.raw) 2>/dev/null | sed -e 's/^.*uid://' | sort | uniq -c | wc -l);
        tally=$(ls -1 $basedir/data/$vote/tally/*.raw 2>/dev/null | wc -l; )
        outfile=$basedir/data/${vote}/timeline/results.$(date +%s).txt
        outgraph=${outfile%%txt}png
        echo "The total numbers of votes tallied = $uids" >> $basedir/data/${vote}/results.txt
        if [ -d $basedir/data/${vote}/timeline ]; then
            cp -f $basedir/data/${vote}/results.txt $outfile
            cp -f $basedir/data/${vote}/results.png $outgraph
        fi

        echo cleaning up
        find $basedir/data/${vote}/tmp/ -type f -exec rm {} \;
    fi
done
